name: "Setup AWS CLI"
author: "Sumanshu Nankana"
description: "This is to Setup and Configure AWS CLI"
inputs:
  region:
    description: "AWS Default region"
    required: true
  aws-access-key:
    description: "This is access key for AWS CLI"
    required: true
  aws-secret-access-key:
    description: "This is secret key for AWS CLI"
    required: true
runs:
  using: "composite"
  steps:
    - name: "Setup AWS CLI"
      shell: bash
      run: |
        python -m venv .venv
        source .venv/bin/activate
        pip install awscli
        aws configure set default.region ${{ inputs.region }}
        aws configure set aws_access_key_id ${{ inputs.aws-access-key }}
        aws configure set aws_secret_access_key ${{ inputs.aws-secret-access-key }}
    - name: Check AWS CLI Version
      shell: bash
      run: aws --version
