name: 1. Basic Workflow
run-name:  ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  workflow_dispatch
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Starting Workflow
        run: echo "Starting my first job"

      - name: Checking the runner
        run: echo "The workflow is running on ${{ runner.os }} hosted by GitHub.

      - name: Checkout the Repo
        uses: actions/checkout@v4

      - name: List the content of repo
        run: |
          echo "Below are the list of files" 
          ls ${{ github.workspace }}

      - name: Setting up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Checking Python Installed Version
        run: python --version

