name: 1. Basic Workflow
on:
  workflow_dispatch
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Starting Workflow
        run: echo "Starting my first job"

      - name: Checkout the Repo
        uses: actions/checkout@v4

      - name: List the content of repo
        run: ls ${{ github.workspace }}

