name: 15. Publish Docker Image into DockerHub
run-name: ${{ github.actor }} is running the ${{ github.workflow }}
on:
  - workflow_dispatch

jobs:
  publish-docker-image:
    runs-on: ubuntu-latest

    steps:
      - name: Login into the Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push the Image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: sumanshunankana/my-python-app:latest