name: 16. Publish Docker Image into GHCR.IO
run-name: ${{ github.actor }} is running the ${{ github.workflow }}
on:
  - workflow_dispatch

jobs:
  publish-docker-image:
    runs-on: ubuntu-latest

#    permissions:
#      packages: write

    steps:
      - name: Login into the github container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push the Image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ghcr.io/sumanshu-nankana/github-actions-demo:latest