name: 2. Variables
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  workflow_dispatch
env:
  GREETING: "Namastey"
  NAME: ${{ vars.WELCOME }}


jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Printing the Repository Variables
        run: echo "The value of WELCOME is ${{ vars.WELCOME }}"

      - name: Setting Up and Printing the Environment Variables
        run: echo "The first name is ${{ env.FIRSTNAME }} and last name is ${{ env.LASTNAME }}"
        env:
          FIRSTNAME: "Sumanshu"
          LASTNAME: "Nankana"

      - name: Printing the Workflow Environment Variables
        run: |
          echo "The value of GREETING env vars is ${{ env.GREETING }}"
          echo "The value of NAME env vars is ${{ env.NAME }}"