name: 6. Expression Status Check
run-name: ${{ github.actor }} is running the ${{ github.workflow }}
on:
  - workflow_dispatch


jobs:
  unit-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependecies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --with dev --no-root

      - name: Run Test and Generate HTML Report
        run: poetry run pytest --html=result.html

      - name: Store the HTML Report to artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: unittest-report.html
          path: result.html
          retention-days: 1
