name: 8. Reusable Worfklow
run-name: ${{ github.actor }} is running the ${{ github.workflow }}
on:
  - workflow_dispatch


jobs:
  unit-test:
    uses: ./.github/workflows/Common Workflow.yaml

  second-job:
    runs-on: ubuntu-latest
    needs: unit-test
    continue-on-error: true

    steps:
      - name: First Step
        run: echo "This is first step of second job"

      - name: Second Step
        run: |
          echo "This is second step for second job"
          exit 1

  third-job:
    runs-on: ubuntu-latest
    needs: second-job
    timeout-minutes: 1

    steps:
      - name: First Step
        run: echo "This is first step for second job"

      - name: Second Step
        run: sleep 80